---
- name: Add apt-key for docker repo
  apt_key:
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D
    state: present

- name: Add docker apt repo
  apt_repository:
    repo: "deb https://apt.dockerproject.org/repo ubuntu-trusty main"
    state: present

- name: Install Docker
  apt:
    name: docker-engine
    state: present
    update_cache: yes

- name: Start Docker
  command: "service docker restart"

